/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AvisoLegalRouteImport } from './routes/aviso-legal'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as NuestrosProyectosRouteImport } from './routes/nuestros-proyectos'
import { Route as OtrosServiciosRouteImport } from './routes/otros-servicios'
import { Route as PoliticaCookiesRouteImport } from './routes/politica-cookies'
import { Route as PoliticaPrivacidadRouteImport } from './routes/politica-privacidad'
import { Route as ReformasBanosRouteImport } from './routes/reformas-banos'
import { Route as ReformasCocinasRouteImport } from './routes/reformas-cocinas'
import { Route as ReformasIntegralesRouteImport } from './routes/reformas-integrales'
import { Route as ReformasLocalesRouteImport } from './routes/reformas-locales'
import { Route as ReformasPisosRouteImport } from './routes/reformas-pisos'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AvisoLegalRoute = AvisoLegalRouteImport.update({
  id: '/aviso-legal',
  path: '/aviso-legal',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const NuestrosProyectosRoute = NuestrosProyectosRouteImport.update({
  id: '/nuestros-proyectos',
  path: '/nuestros-proyectos',
  getParentRoute: () => rootRouteImport,
} as any)
const OtrosServiciosRoute = OtrosServiciosRouteImport.update({
  id: '/otros-servicios',
  path: '/otros-servicios',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaCookiesRoute = PoliticaCookiesRouteImport.update({
  id: '/politica-cookies',
  path: '/politica-cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaPrivacidadRoute = PoliticaPrivacidadRouteImport.update({
  id: '/politica-privacidad',
  path: '/politica-privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const ReformasBanosRoute = ReformasBanosRouteImport.update({
  id: '/reformas-banos',
  path: '/reformas-banos',
  getParentRoute: () => rootRouteImport,
} as any)
const ReformasCocinasRoute = ReformasCocinasRouteImport.update({
  id: '/reformas-cocinas',
  path: '/reformas-cocinas',
  getParentRoute: () => rootRouteImport,
} as any)
const ReformasIntegralesRoute = ReformasIntegralesRouteImport.update({
  id: '/reformas-integrales',
  path: '/reformas-integrales',
  getParentRoute: () => rootRouteImport,
} as any)
const ReformasLocalesRoute = ReformasLocalesRouteImport.update({
  id: '/reformas-locales',
  path: '/reformas-locales',
  getParentRoute: () => rootRouteImport,
} as any)
const ReformasPisosRoute = ReformasPisosRouteImport.update({
  id: '/reformas-pisos',
  path: '/reformas-pisos',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aviso-legal': typeof AvisoLegalRoute
  '/contacto': typeof ContactoRoute
  '/nuestros-proyectos': typeof NuestrosProyectosRoute
  '/otros-servicios': typeof OtrosServiciosRoute
  '/politica-cookies': typeof PoliticaCookiesRoute
  '/politica-privacidad': typeof PoliticaPrivacidadRoute
  '/reformas-banos': typeof ReformasBanosRoute
  '/reformas-cocinas': typeof ReformasCocinasRoute
  '/reformas-integrales': typeof ReformasIntegralesRoute
  '/reformas-locales': typeof ReformasLocalesRoute
  '/reformas-pisos': typeof ReformasPisosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aviso-legal': typeof AvisoLegalRoute
  '/contacto': typeof ContactoRoute
  '/nuestros-proyectos': typeof NuestrosProyectosRoute
  '/otros-servicios': typeof OtrosServiciosRoute
  '/politica-cookies': typeof PoliticaCookiesRoute
  '/politica-privacidad': typeof PoliticaPrivacidadRoute
  '/reformas-banos': typeof ReformasBanosRoute
  '/reformas-cocinas': typeof ReformasCocinasRoute
  '/reformas-integrales': typeof ReformasIntegralesRoute
  '/reformas-locales': typeof ReformasLocalesRoute
  '/reformas-pisos': typeof ReformasPisosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aviso-legal': typeof AvisoLegalRoute
  '/contacto': typeof ContactoRoute
  '/nuestros-proyectos': typeof NuestrosProyectosRoute
  '/otros-servicios': typeof OtrosServiciosRoute
  '/politica-cookies': typeof PoliticaCookiesRoute
  '/politica-privacidad': typeof PoliticaPrivacidadRoute
  '/reformas-banos': typeof ReformasBanosRoute
  '/reformas-cocinas': typeof ReformasCocinasRoute
  '/reformas-integrales': typeof ReformasIntegralesRoute
  '/reformas-locales': typeof ReformasLocalesRoute
  '/reformas-pisos': typeof ReformasPisosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aviso-legal'
    | '/contacto'
    | '/nuestros-proyectos'
    | '/otros-servicios'
    | '/politica-cookies'
    | '/politica-privacidad'
    | '/reformas-banos'
    | '/reformas-cocinas'
    | '/reformas-integrales'
    | '/reformas-locales'
    | '/reformas-pisos'
    | '/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aviso-legal'
    | '/contacto'
    | '/nuestros-proyectos'
    | '/otros-servicios'
    | '/politica-cookies'
    | '/politica-privacidad'
    | '/reformas-banos'
    | '/reformas-cocinas'
    | '/reformas-integrales'
    | '/reformas-locales'
    | '/reformas-pisos'
    | '/sitemap.xml'
  id:
    | '__root__'
    | '/'
    | '/aviso-legal'
    | '/contacto'
    | '/nuestros-proyectos'
    | '/otros-servicios'
    | '/politica-cookies'
    | '/politica-privacidad'
    | '/reformas-banos'
    | '/reformas-cocinas'
    | '/reformas-integrales'
    | '/reformas-locales'
    | '/reformas-pisos'
    | '/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AvisoLegalRoute: typeof AvisoLegalRoute
  ContactoRoute: typeof ContactoRoute
  NuestrosProyectosRoute: typeof NuestrosProyectosRoute
  OtrosServiciosRoute: typeof OtrosServiciosRoute
  PoliticaCookiesRoute: typeof PoliticaCookiesRoute
  PoliticaPrivacidadRoute: typeof PoliticaPrivacidadRoute
  ReformasBanosRoute: typeof ReformasBanosRoute
  ReformasCocinasRoute: typeof ReformasCocinasRoute
  ReformasIntegralesRoute: typeof ReformasIntegralesRoute
  ReformasLocalesRoute: typeof ReformasLocalesRoute
  ReformasPisosRoute: typeof ReformasPisosRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aviso-legal': {
      id: '/aviso-legal'
      path: '/aviso-legal'
      fullPath: '/aviso-legal'
      preLoaderRoute: typeof AvisoLegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nuestros-proyectos': {
      id: '/nuestros-proyectos'
      path: '/nuestros-proyectos'
      fullPath: '/nuestros-proyectos'
      preLoaderRoute: typeof NuestrosProyectosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/otros-servicios': {
      id: '/otros-servicios'
      path: '/otros-servicios'
      fullPath: '/otros-servicios'
      preLoaderRoute: typeof OtrosServiciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-cookies': {
      id: '/politica-cookies'
      path: '/politica-cookies'
      fullPath: '/politica-cookies'
      preLoaderRoute: typeof PoliticaCookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-privacidad': {
      id: '/politica-privacidad'
      path: '/politica-privacidad'
      fullPath: '/politica-privacidad'
      preLoaderRoute: typeof PoliticaPrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reformas-banos': {
      id: '/reformas-banos'
      path: '/reformas-banos'
      fullPath: '/reformas-banos'
      preLoaderRoute: typeof ReformasBanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reformas-cocinas': {
      id: '/reformas-cocinas'
      path: '/reformas-cocinas'
      fullPath: '/reformas-cocinas'
      preLoaderRoute: typeof ReformasCocinasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reformas-integrales': {
      id: '/reformas-integrales'
      path: '/reformas-integrales'
      fullPath: '/reformas-integrales'
      preLoaderRoute: typeof ReformasIntegralesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reformas-locales': {
      id: '/reformas-locales'
      path: '/reformas-locales'
      fullPath: '/reformas-locales'
      preLoaderRoute: typeof ReformasLocalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reformas-pisos': {
      id: '/reformas-pisos'
      path: '/reformas-pisos'
      fullPath: '/reformas-pisos'
      preLoaderRoute: typeof ReformasPisosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AvisoLegalRoute: AvisoLegalRoute,
  ContactoRoute: ContactoRoute,
  NuestrosProyectosRoute: NuestrosProyectosRoute,
  OtrosServiciosRoute: OtrosServiciosRoute,
  PoliticaCookiesRoute: PoliticaCookiesRoute,
  PoliticaPrivacidadRoute: PoliticaPrivacidadRoute,
  ReformasBanosRoute: ReformasBanosRoute,
  ReformasCocinasRoute: ReformasCocinasRoute,
  ReformasIntegralesRoute: ReformasIntegralesRoute,
  ReformasLocalesRoute: ReformasLocalesRoute,
  ReformasPisosRoute: ReformasPisosRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
